name: palabramania
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.13.3
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/audios/
    - assets/audios/correcto.mp3
    - assets/audios/error.mp3
    - assets/ahorcado/
    - assets/avatars/
